// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaJNUHAYB1jbn9CT0-ycf6RMQd7o50t10',
    appId: '1:286895014988:web:9819b19e7bd3931db0e0e9',
    messagingSenderId: '286895014988',
    projectId: 'hitech-instagram-clone',
    authDomain: 'hitech-instagram-clone.firebaseapp.com',
    storageBucket: 'hitech-instagram-clone.appspot.com',
    measurementId: 'G-C1KN1PC6SG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1vy-5qlA8X9slA9xYvVn2DWjeeWSTydw',
    appId: '1:286895014988:android:53ede7c406b65c62b0e0e9',
    messagingSenderId: '286895014988',
    projectId: 'hitech-instagram-clone',
    storageBucket: 'hitech-instagram-clone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtrPQb0yXNdBHZyQt-PsHIWhbMIw1qJ_g',
    appId: '1:286895014988:ios:25ab2afb6b03fca2b0e0e9',
    messagingSenderId: '286895014988',
    projectId: 'hitech-instagram-clone',
    storageBucket: 'hitech-instagram-clone.appspot.com',
    iosBundleId: 'tech.hidetora.instagramClone',
  );
}
